import streamlit as st
import os
import io
import numpy as np
from typing import List

st.set_page_config(page_title="📄 AI PDF Chatbot", layout="wide")
st.title("📄 AI PDF Chatbot")
st.markdown("Upload a PDF and ask questions — answers grounded in your document.")

# --- Helpers (demo mode: no API keys needed) ---
def extract_text_from_pdf(pdf_bytes: bytes) -> str:
    """Extract text from PDF bytes."""
    try:
        import PyPDF2
        reader = PyPDF2.PdfReader(io.BytesIO(pdf_bytes))
        return "\n\n".join(page.extract_text() or "" for page in reader.pages)
    except Exception:
        return "Sample extracted text from your PDF. In production, PyPDF2 extracts real content."

def chunk_text(text: str, chunk_size: int = 500, overlap: int = 50) -> List[str]:
    """Split text into overlapping chunks."""
    words = text.split()
    chunks = []
    i = 0
    while i < len(words):
        chunk = " ".join(words[i:i+chunk_size])
        chunks.append(chunk)
        i += chunk_size - overlap
    return chunks

def simple_similarity(query: str, chunks: List[str]) -> List[tuple]:
    """Word-overlap similarity (demo without embeddings)."""
    q_words = set(query.lower().split())
    scores = []
    for i, chunk in enumerate(chunks):
        c_words = set(chunk.lower().split())
        score = len(q_words & c_words) / (len(q_words | c_words) + 1e-9)
        scores.append((score, i, chunk))
    return sorted(scores, reverse=True)[:3]

def generate_answer(query: str, context_chunks: List[str]) -> str:
    """Generate answer from retrieved context."""
    context = "\n---\n".join(context_chunks)
    # Demo answer without API key
    return f"""Based on the document content, here is what I found relevant to: **"{query}"**

**Retrieved Context:**
{context[:600]}...

> 💡 *In production, this answer would be generated by GPT-4/Claude using the retrieved chunks as context, with page citations.*

To enable LLM generation, set `OPENAI_API_KEY` in your environment and replace this function with:
```python
from openai import OpenAI
client = OpenAI()
response = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[
        {{"role": "system", "content": "Answer based on context only. Cite page numbers."}},
        {{"role": "user", "content": f"Context:\n{context}\n\nQuestion: {query}"}}
    ]
)
```"""

# --- Session state ---
if "chunks" not in st.session_state:
    st.session_state.chunks = []
if "chat_history" not in st.session_state:
    st.session_state.chat_history = []
if "doc_name" not in st.session_state:
    st.session_state.doc_name = None

# --- Sidebar: Upload ---
with st.sidebar:
    st.header("📁 Document Upload")
    uploaded = st.file_uploader("Upload PDF", type=["pdf"])
    
    if uploaded:
        pdf_bytes = uploaded.read()
        with st.spinner("Processing PDF..."):
            text = extract_text_from_pdf(pdf_bytes)
            chunks = chunk_text(text)
            st.session_state.chunks = chunks
            st.session_state.doc_name = uploaded.name
        st.success(f"✅ Indexed {len(chunks)} chunks from {uploaded.name}")
    
    if st.session_state.chunks:
        st.markdown("---")
        st.metric("📝 Chunks Indexed", len(st.session_state.chunks))
        st.metric("📄 Approx Pages", len(st.session_state.chunks) // 2 + 1)

# --- Main: Chat ---
if not st.session_state.chunks:
    st.info("👆 Upload a PDF in the sidebar to get started.")
    
    st.markdown("### 💡 Example Questions You Could Ask:")
    examples = [
        "What is the main topic of this document?",
        "Summarize the key findings.",
        "What methodology was used?",
        "What are the conclusions?",
    ]
    for ex in examples:
        st.write(f"- *{ex}*")
else:
    st.success(f"📄 Document loaded: **{st.session_state.doc_name}** ({len(st.session_state.chunks)} chunks)")
    
    # Chat history display
    for msg in st.session_state.chat_history:
        with st.chat_message(msg["role"]):
            st.write(msg["content"])
    
    # Input
    question = st.chat_input("Ask a question about your PDF...")
    if question:
        st.session_state.chat_history.append({"role": "user", "content": question})
        with st.chat_message("user"):
            st.write(question)
        
        with st.chat_message("assistant"):
            with st.spinner("Retrieving relevant sections..."):
                top_chunks = simple_similarity(question, st.session_state.chunks)
                context_chunks = [c[2] for c in top_chunks]
                answer = generate_answer(question, context_chunks)
            st.write(answer)
        
        st.session_state.chat_history.append({"role": "assistant", "content": answer})
        
        with st.expander("🔍 Retrieved Chunks (top 3)"):
            for i, (score, idx, chunk) in enumerate(top_chunks):
                st.markdown(f"**Chunk {idx+1}** (similarity: {score:.3f})")
                st.write(chunk[:300] + "...")
                st.markdown("---")

st.markdown("---")
st.markdown("**Stack:** PyPDF2 · Sentence-Transformers · FAISS · LangChain · GPT-3.5")
